pull_request_rules:
  - name: Automatic merge when CI passes and labeled
    conditions:
      - check-success = fast-build
      - label = mergify-merge
      - base = main
    actions:
      merge:
