---
on:
  push: {}

jobs:
  fast-build:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          # build-mount-path: "/nix"
          temp-reserve-mb: 512
          root-reserve-mb: 512
          swap-size-mb: 1024
      - uses: actions/checkout@v2.5.0
        with:
          submodules: "recursive"
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          kvm: true
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - uses: cachix/cachix-action@v14
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: nialov
      - name: "Evaluate and build checks faster"
        run: |
          nix run .#nix-fast-build -- --no-nom --skip-cached
