---
on:
  push: {}
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm
      # - uses: cachix/install-nix-action@v18
      #   with:
      #     nix_path: nixpkgs=channel:nixos-unstable
      #     install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      #     extra_nix_config: |
      #       system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v12
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: nialov
      - name: "Check flake"
        run: |
          nix -Lv flake check --show-trace
