jobs:
  nix-fast-build:
    runs-on: ubuntu-latest
    steps:
    - uses: easimon/maximize-build-space@master
      with:
        build-mount-path: /nix
        remove-android: true
        remove-codeql: true
        remove-docker-images: true
        remove-dotnet: true
        remove-haskell: true
        root-reserve-mb: 1024
        swap-size-mb: 2048
        temp-reserve-mb: 1024
    - name: Reown /nix to root
      run: sudo chown -R root /nix
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v9
    - uses: cachix/cachix-action@v14
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: nialov
    - uses: DeterminateSystems/nix-installer-action@v9
    - name: Evaluate and build checks faster
      run: nix run .#nix-fast-build -- --no-nom --skip-cached
    timeout-minutes: 60
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v9
    - name: Check flake
      run: nix -Lv flake check --no-build
    timeout-minutes: 60
'on':
  push: {}
  workflow_dispatch: {}
