---
on:
  push: {}
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm
      - name: Run the magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v12
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: nialov
      - name: "Check flake"
        run: |
          nix flake check
