jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - continue-on-error: true
      uses: cachix/cachix-action@v14
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: nialov
    - uses: DeterminateSystems/nix-installer-action@v9
    - name: Build ${{ github.event.inputs.package }}
      run: nix build .#${{ github.event.inputs.package }}
    timeout-minutes: 60
'on':
  workflow_dispatch:
    inputs:
      package:
        description: Nix package name to build (e.g., hello)
        required: true
